name: Azure Deploy

on: 
 push: 
  branches:
   - main
  paths:
    - infrastructure/**
 pull_request:
  branches:
    - main
  paths:
    - infrastructure/**
 workflow_dispatch: # manual trigger

permissions:
  id-token: write
  contents: read

jobs:
 deploy-dev:
  runs-on: ubuntu-latest
  environment: Development
  steps:
    - uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: Azure/CLI@v2
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
          echo "Azure resource group created"

    - name: Deploy  
      id: deploy
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
        template: ./infrastructure/main.bicep

    - name: Assign Key Vault Permissions
      uses: Azure/CLI@v2
      with:
        inlineScript: |
          #!/bin/bash
          # Get deployment outputs
          KEY_VAULT_NAME=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.keyVaultName.value' -o tsv)
          PRINCIPAL_ID=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.appServicePrincipalId.value' -o tsv)
          
          # Assign Key Vault Secrets User role
          az role assignment create \
            --assignee $PRINCIPAL_ID \
            --role "Key Vault Secrets User" \
            --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP_NAME }}/providers/Microsoft.KeyVault/vaults/$KEY_VAULT_NAME"
          
          echo "Key Vault permissions assigned successfully"

 deploy-stg:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: Staging
    steps:
      - uses: actions/checkout@v4
  
      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"
  
      - name: Deploy  
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep

      - name: Assign Key Vault Permissions
        uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            # Get deployment outputs
            KEY_VAULT_NAME=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.keyVaultName.value' -o tsv)
            PRINCIPAL_ID=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.appServicePrincipalId.value' -o tsv)
            
            # Assign Key Vault Secrets User role
            az role assignment create \
              --assignee $PRINCIPAL_ID \
              --role "Key Vault Secrets User" \
              --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP_NAME }}/providers/Microsoft.KeyVault/vaults/$KEY_VAULT_NAME"
            
            echo "Key Vault permissions assigned successfully"


 deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-stg
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: Production
    steps:
      - uses: actions/checkout@v4
  
      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"
  
      - name: Deploy  
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep

      - name: Assign Key Vault Permissions
        uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            # Get deployment outputs
            KEY_VAULT_NAME=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.keyVaultName.value' -o tsv)
            PRINCIPAL_ID=$(az deployment group show --name ${{ steps.deploy.outputs.deploymentName }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --query 'properties.outputs.appServicePrincipalId.value' -o tsv)
            
            # Assign Key Vault Secrets User role
            az role assignment create \
              --assignee $PRINCIPAL_ID \
              --role "Key Vault Secrets User" \
              --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP_NAME }}/providers/Microsoft.KeyVault/vaults/$KEY_VAULT_NAME"
            
            echo "Key Vault permissions assigned successfully"
